ElevenNote/ElevenNote.Web/Controllers/NotesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ElevenNote.Models;
using ElevenNote.Services;
using Microsoft.AspNet.Identity;

namespace ElevenNote.Web.Controllers
{
    [Authorize]
    public class NotesController : Controller
    {
        private readonly Lazy<NoteService> _svc;

        public NotesController()
        {
            _svc =
                new Lazy<NoteService>(
                    () =>
                    {
                        var userId = Guid.Parse(User.Identity.GetUserId());
                        return new NoteService(userId);
                    });
        }

        public ActionResult Index()
        {
            var notes = _svc.Value.GetNotes();

            return View(notes);
        }

        public ActionResult Create()
        {
            var vm = new NoteCreateViewModel();

            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(NoteCreateViewModel vm)
        {
            if (!ModelState.IsValid) return View(vm);

            if(!_svc.Value.CreateNote(vm))
            {
                ModelState.AddModelError("", "Unable to create note");
                return View(vm);
            }

            return RedirectToAction("Index");
        }

        public ActionResult Details(int id)
        {
            var note = _svc.Value.GetNoteById(id);

            return View(note);
        }

        public ActionResult Edit(int id)
        {
            var detail = _svc.Value.GetNoteById(id);
            var note =
                new NoteEditViewModel
                {
                    NoteId = detail.NoteId,
                    Title = detail.Title,
                    Content = detail.Content,
                    IsStarred = detail.IsStarred
                };

            return View(note);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(NoteEditViewModel vm)
        {
            if (!ModelState.IsValid) return View(vm);

            if(!_svc.Value.UpdateNote(vm))
            {
                ModelState.AddModelError("", "Unable to update note");
                return View(vm);
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        [ActionName("Delete")]
        public ActionResult DeleteGet(int id)
        {
            var detail = _svc.Value.GetNoteById(id);

            return View(detail);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePost(int id)
        {
            _svc.Value.DeleteNote(id);

            return RedirectToAction("Index");
        }
    }
}

ElevenNote/ElevenNote.Web/Controllers/WebApi/NotesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using ElevenNote.Models;
using ElevenNote.Services;
using Microsoft.AspNet.Identity;

namespace ElevenNote.Web.Controllers.WebApi
{
    [Authorize]
    [RoutePrefix("api/Notes")]
    public class NotesController : ApiController
    {
        private readonly Lazy<NoteService> _svc;

        public NotesController()
        {
            _svc =
                new Lazy<NoteService>(
                    () =>
                    {
                        var userId = Guid.Parse(User.Identity.GetUserId());
                        return new NoteService(userId);
                    });
        }

        [Route]
        public IEnumerable<NoteListItemViewModel> Get()
        {
            return _svc.Value.GetNotes();
        }

        [Route]
        public bool Post(NoteCreateViewModel vm)
        {
            return _svc.Value.CreateNote(vm);
        }

        [Route("{id}")]
        public NoteDetailViewModel Get(int id)
        {
            return _svc.Value.GetNoteById(id);
        }

        [Route("{id}")]
        public bool Put(int id, NoteEditViewModel vm)
        {
            return _svc.Value.UpdateNote(vm);
        }

        [Route("{id}")]
        public bool Delete(int id)
        {
            return _svc.Value.DeleteNote(id);
        }

        private bool SetStarState(int noteId, bool state)
        {
            var detail =
                _svc
                    .Value
                    .GetNoteById(noteId);

            var note =
                new NoteEditViewModel
                {
                    NoteId = detail.NoteId,
                    Title = detail.Title,
                    Content = detail.Content,
                    IsStarred = state
                };

            return _svc.Value.UpdateNote(note);
        }

        [Route("{id}/Star")]
        [HttpPost]
        public bool ToggleStarOn(int id)
        {
            return SetStarState(id, true);
        }

        [Route("{id}/Star")]
        [HttpDelete]
        public bool ToggleStarOff(int id)
        {
            return SetStarState(id, false);
        }
    }
}

ElevenNote/ElevenNote.Web/Views/Notes/Create.cshtml
@model ElevenNote.Models.NoteCreateViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>NoteCreateViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ElevenNote/ElevenNote.Web/Views/Notes/Delete.cshtml
@model ElevenNote.Models.NoteDetailViewModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>NoteDetailViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NoteId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NoteId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Content)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsStarred)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsStarred)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedUtc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedUtc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedUtc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedUtc)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ElevenNote/ElevenNote.Web/Views/Notes/Details.cshtml
@model ElevenNote.Models.NoteDetailViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>NoteDetailViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NoteId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NoteId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Content)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsStarred)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsStarred)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedUtc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedUtc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedUtc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedUtc)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.NoteId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ElevenNote/ElevenNote.Web/Views/Notes/Edit.cshtml
@model ElevenNote.Models.NoteEditViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>NoteEditViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.NoteId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NoteId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NoteId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsStarred, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsStarred)
                    @Html.ValidationMessageFor(model => model.IsStarred, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ElevenNote/ElevenNote.Web/Views/Notes/Index.cshtml
@model IEnumerable<ElevenNote.Models.NoteListItemViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p class="text-right">
    @Html.ActionLink("Create New", "Create", "Notes", new { @class = "btn btn-primary" })
</p>
<table class="table">
    <tr>
        <th></th>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsStarred)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedUtc)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            <div class="btn-group btn-group-xs">
                <button type="button" class="btn btn-xs btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="glyphicon glyphicon-cog"></i> <span class="caret"></span>
                </button>
                <ul class="dropdown-menu">
                    <li>@Html.ActionLink("Edit", "Edit", new { id = item.NoteId })</li>
                    <li>@Html.ActionLink("Delete", "Delete", new { id = item.NoteId })</li>
                </ul>
            </div>
        </td>
        <td>
            @Html.ActionLink(item.Title, "Details", new { id = item.NoteId })
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsStarred, new { Id = item.NoteId })
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreatedUtc)
        </td>
    </tr>
}

</table>

@section scripts {
    <script language="javascript" type="text/javascript">
        $(document).ready(function () {
            $("i[data-toggle='star']")
                .css({ "cursor": "pointer" })
                .click(function (e) {
                    var target = $(e.target);
                    var noteId = target.attr("data-id");
                    var starSet = target.hasClass("glyphicon-star");

                    $.ajax({
                        method: starSet ? "DELETE" : "POST",
                        url: "/api/notes/" + noteId + "/star",
                        data: null
                    })
                    .done(function (r) { target.removeClass(); target.addClass("glyphicon " + (starSet ? "glyphicon-star-empty" : "glyphicon-star")); })
                    .fail(function (r) { alert("Failed to change star status"); });
                });
        });
    </script>
}